edition = "2021"
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
match_block_trailing_comma = true
max_width = 120
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 20
