[bans]
skip = [{ name = "base64" }, { name = "windows-sys" }]

[graph]
all-features = true

[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "MPL-2.0",
  "OpenSSL",
  "Unlicense",
]
confidence-threshold = 1.0
exceptions = [{ crate = "unicode-ident", allow = ["Unicode-DFS-2016"] }]
clarify = [
  # see https://github.com/briansmith/ring/blob/main/LICENSE for details
  { crate = "ring", expression = "MIT AND ISC AND OpenSSL", license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
  ] },
]
unused-allowed-license = "allow"

[sources]
allow-git = [ "https://github.com/SuperSandro2000/octocrab.git" ]
