name: Checks
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
permissions:
  checks: write
  contents: read
env:
  RUSTFLAGS: "-Dwarnings"
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Check for spelling errors
        uses: reviewdog/action-misspell@v1
        with:
          exclude: ./vendor/*
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ignore: importas
          reporter: github-check
      # - name: Check if source code files have license header
      #   run: make check-license-headers
      # this action runs pretty late, to collect previous errors when new advisories arive
      - uses: EmbarkStudios/cargo-deny-action@v2
      # https://doc.rust-lang.org/stable/clippy/continuous_integration/github_actions.html
